export const DataProduct = [
    {
        id : 1,
        title: 'Moto G200',
        price: 69999.99,
        stock: 5,
        image: '../assets/motog200.png',
        category: 'MotoG',
    },
    {
        id : 2,
        title: 'Moto G71',
        price: 79999.99,
        stock: 4,
        image: '../assets/motog71.png',
        category: 'MotoG',
    },
    {
        id : 3,
        title: 'Moto G60',
        price: 89999.99,
        stock: 10,
        image: '../assets/motog60s.png',
        category: 'MotoG',
    },
    {
        id : 4,
        title: 'Moto G51',
        price: 89999.99,
        stock: 10,
        image: '../assets/motog51.png',
        category: 'MotoG',
    },
    {
        id : 5,
        title: 'Moto E7',
        price: 69999.99,
        stock: 5,
        image: '../assets/motoe7.png',
        category: 'MotoE',
    },
    {
        id : 6,
        title: 'Moto E20',
        price: 79999.99,
        stock: 4,
        image: '../assets/motoe20.png',
        category: 'MotoE',
    },
    {
        id : 7,
        title: 'Moto E40',
        price: 89999.99,
        stock: 10,
        image: '../assets/motoe40.png',
        category: 'MotoE',
    },
    {
        id : 8,
        title: 'Moto E71I',
        price: 89999.99,
        stock: 10,
        image: '../assets/motoe71i.png',
        category: 'MotoE',
    },

];